In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],

    "temperature_C": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],

    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],

    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [ ]:
df

    soil_moisture  temperature_C  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [ ]:
df.columns

Index(['soil_moisture', 'temperature_C', 'sunlight_hours', 'needs_water'], dtype='object')

In [ ]:
x = df[['soil_moisture', 'temperature_C', 'sunlight_hours']]
y = df['needs_water']

In [ ]:
x_min = x.min()
x_max = x.max()
x_scaled = (x-x_min) / (x_max-x_min+1e-8)

In [ ]:
x_scaled

    soil_moisture  temperature_C  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x_scaled,y,test_size=0.25,random_state=42, stratify=y)

In [ ]:
model = keras.Sequential([
    layers.Input(shape = (x_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation= 'sigmoid')

])

In [ ]:
model.compile(optimizer="sgd",loss = 'binary_crossentropy',metrics = ['accuracy'])

In [ ]:
history = model.fit(x_train.values, y_train.values,
                    validation_data=(x_test.values, y_test.values),
                    epochs=100, batch_size=4, verbose=1)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 104ms/step - accuracy: 0.4062 - loss: 0.6977 - val_accuracy: 0.5000 - val_loss: 0.7001
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.4688 - loss: 0.6924 - val_accuracy: 0.5000 - val_loss: 0.6984
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.4375 - loss: 0.6940 - val_accuracy: 0.5000 - val_loss: 0.6969
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.4688 - loss: 0.6904 - val_accuracy: 0.5000 - val_loss: 0.6954
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5000 - loss: 0.6798 - val_accuracy: 0.5000 - val_loss: 0.6938
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5000 - loss: 0.6837 - val_accuracy: 0.7500 - val_loss: 0.6923
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5312 - loss: 0.6771 - val_accuracy: 0.7500 - val_loss: 0.6907
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5625 - loss: 0.6728 - val_accuracy: 0.7500 - val_loss: 0.6892
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5938 - loss: 0.6649 - val_accuracy: 0.5000 - val_loss: 0.6878
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.4062 - loss: 0.6910 - val_accuracy: 0.5000 - val_loss: 0.6864
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.3750 - loss: 0.6902 - val_accuracy: 0.5000 - val_loss: 0.6850
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6562 - loss: 0.6540 - val_accuracy: 0.5000 - val_loss: 0.6836
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5938 - loss: 0.6634 - val_accuracy: 0.5000 - val_loss: 0.6822
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5312 - loss: 0.6688 - val_accuracy: 0.5000 - val_loss: 0.6808
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5312 - loss: 0.6665 - val_accuracy: 0.5000 - val_loss: 0.6794
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.4375 - loss: 0.6754 - val_accuracy: 0.5000 - val_loss: 0.6780
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5625 - loss: 0.6624 - val_accuracy: 0.5000 - val_loss: 0.6767
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6702 - val_accuracy: 0.5000 - val_loss: 0.6755
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6598 - val_accuracy: 0.5000 - val_loss: 0.6742
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.4062 - loss: 0.6799 - val_accuracy: 0.5000 - val_loss: 0.6730
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.4688 - loss: 0.6643 - val_accuracy: 0.5000 - val_loss: 0.6718
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5104 - loss: 0.6710 - val_accuracy: 0.5000 - val_loss: 0.6708
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5938 - loss: 0.6550 - val_accuracy: 0.5000 - val_loss: 0.6697
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.4688 - loss: 0.6708 - val_accuracy: 0.5000 - val_loss: 0.6687
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5417 - loss: 0.6717 - val_accuracy: 0.5000 - val_loss: 0.6677
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5521 - loss: 0.6747 - val_accuracy: 0.5000 - val_loss: 0.6667
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5417 - loss: 0.6588 - val_accuracy: 0.5000 - val_loss: 0.6657
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5104 - loss: 0.6715 - val_accuracy: 0.5000 - val_loss: 0.6647
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6771 - loss: 0.6625 - val_accuracy: 0.5000 - val_loss: 0.6637
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6771 - loss: 0.6543 - val_accuracy: 0.5000 - val_loss: 0.6627
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5521 - loss: 0.6667 - val_accuracy: 0.5000 - val_loss: 0.6617
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.7083 - loss: 0.6611 - val_accuracy: 0.7500 - val_loss: 0.6606
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7396 - loss: 0.6460 - val_accuracy: 0.7500 - val_loss: 0.6594
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.8021 - loss: 0.6421 - val_accuracy: 0.7500 - val_loss: 0.6582
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6458 - loss: 0.6610 - val_accuracy: 0.7500 - val_loss: 0.6571
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5833 - loss: 0.6514 - val_accuracy: 0.7500 - val_loss: 0.6559
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6771 - loss: 0.6457 - val_accuracy: 0.7500 - val_loss: 0.6548
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6458 - loss: 0.6519 - val_accuracy: 0.7500 - val_loss: 0.6537
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7083 - loss: 0.6448 - val_accuracy: 0.7500 - val_loss: 0.6525
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6771 - loss: 0.6362 - val_accuracy: 0.7500 - val_loss: 0.6513
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6458 - loss: 0.6559 - val_accuracy: 0.7500 - val_loss: 0.6504
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6146 - loss: 0.6613 - val_accuracy: 0.7500 - val_loss: 0.6495
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6645 - val_accuracy: 0.7500 - val_loss: 0.6486
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.6224 - val_accuracy: 0.7500 - val_loss: 0.6476
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6771 - loss: 0.6321 - val_accuracy: 0.7500 - val_loss: 0.6467
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7396 - loss: 0.6346 - val_accuracy: 0.7500 - val_loss: 0.6457
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7396 - loss: 0.6392 - val_accuracy: 0.7500 - val_loss: 0.6448
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7083 - loss: 0.6320 - val_accuracy: 0.7500 - val_loss: 0.6439
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6146 - loss: 0.6493 - val_accuracy: 0.7500 - val_loss: 0.6430
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6466 - val_accuracy: 0.7500 - val_loss: 0.6421
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6146 - loss: 0.6384 - val_accuracy: 0.7500 - val_loss: 0.6413
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7083 - loss: 0.6323 - val_accuracy: 0.7500 - val_loss: 0.6405
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7083 - loss: 0.6258 - val_accuracy: 0.7500 - val_loss: 0.6397
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8021 - loss: 0.6229 - val_accuracy: 0.7500 - val_loss: 0.6389
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7083 - loss: 0.6364 - val_accuracy: 0.7500 - val_loss: 0.6381
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8021 - loss: 0.6252 - val_accuracy: 0.7500 - val_loss: 0.6373
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7083 - loss: 0.6307 - val_accuracy: 0.7500 - val_loss: 0.6364
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6458 - loss: 0.6393 - val_accuracy: 0.7500 - val_loss: 0.6356
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7083 - loss: 0.6241 - val_accuracy: 0.7500 - val_loss: 0.6348
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7188 - loss: 0.6397 - val_accuracy: 0.7500 - val_loss: 0.6340
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7812 - loss: 0.6135 - val_accuracy: 0.7500 - val_loss: 0.6331
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8125 - loss: 0.6321 - val_accuracy: 0.7500 - val_loss: 0.6323
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9271 - loss: 0.6311 - val_accuracy: 0.7500 - val_loss: 0.6316
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9271 - loss: 0.6373 - val_accuracy: 0.7500 - val_loss: 0.6307
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.6506 - val_accuracy: 0.7500 - val_loss: 0.6300
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9583 - loss: 0.6280 - val_accuracy: 0.7500 - val_loss: 0.6291
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9583 - loss: 0.6226 - val_accuracy: 0.7500 - val_loss: 0.6282
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.6354 - val_accuracy: 0.7500 - val_loss: 0.6275
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9583 - loss: 0.6356 - val_accuracy: 0.7500 - val_loss: 0.6267
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9271 - loss: 0.6325 - val_accuracy: 0.7500 - val_loss: 0.6259
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9583 - loss: 0.6180 - val_accuracy: 0.7500 - val_loss: 0.6251
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9271 - loss: 0.6312 - val_accuracy: 0.7500 - val_loss: 0.6242
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.6253 - val_accuracy: 0.7500 - val_loss: 0.6235
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8646 - loss: 0.6350 - val_accuracy: 0.7500 - val_loss: 0.6227
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8646 - loss: 0.6178 - val_accuracy: 0.7500 - val_loss: 0.6218
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9271 - loss: 0.6349 - val_accuracy: 0.7500 - val_loss: 0.6211
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8646 - loss: 0.6366 - val_accuracy: 0.7500 - val_loss: 0.6203
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9271 - loss: 0.6319 - val_accuracy: 0.7500 - val_loss: 0.6195
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9583 - loss: 0.5956 - val_accuracy: 0.7500 - val_loss: 0.6186
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.6113 - val_accuracy: 0.7500 - val_loss: 0.6179
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9271 - loss: 0.6289 - val_accuracy: 0.7500 - val_loss: 0.6171
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9271 - loss: 0.6176 - val_accuracy: 0.7500 - val_loss: 0.6162
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9583 - loss: 0.6078 - val_accuracy: 0.7500 - val_loss: 0.6154
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9583 - loss: 0.6109 - val_accuracy: 0.7500 - val_loss: 0.6145
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.6208 - val_accuracy: 0.7500 - val_loss: 0.6137
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.6077 - val_accuracy: 0.7500 - val_loss: 0.6130
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8646 - loss: 0.6303 - val_accuracy: 0.7500 - val_loss: 0.6122
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9583 - loss: 0.5973 - val_accuracy: 0.7500 - val_loss: 0.6114
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8646 - loss: 0.6074 - val_accuracy: 0.7500 - val_loss: 0.6106
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.6162 - val_accuracy: 0.7500 - val_loss: 0.6099
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9583 - loss: 0.6154 - val_accuracy: 0.7500 - val_loss: 0.6090
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.6068 - val_accuracy: 0.7500 - val_loss: 0.6084
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9271 - loss: 0.6179 - val_accuracy: 0.7500 - val_loss: 0.6076
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9583 - loss: 0.5943 - val_accuracy: 1.0000 - val_loss: 0.6068
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9271 - loss: 0.6191 - val_accuracy: 1.0000 - val_loss: 0.6062
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9271 - loss: 0.5986 - val_accuracy: 1.0000 - val_loss: 0.6055
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8646 - loss: 0.6155 - val_accuracy: 1.0000 - val_loss: 0.6048
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5922 - val_accuracy: 1.0000 - val_loss: 0.6043
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.6090 - val_accuracy: 1.0000 - val_loss: 0.6036
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.6049 - val_accuracy: 1.0000 - val_loss: 0.6029